name: merge_to_master
run-name: Merge to master

on:
  push:
    branches:
      - master
      - DAR-2492
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ githFub.ref }}
  cancel-in-progress: true

jobs:

  run_tests:
    name: Run tests
    uses: ./.github/workflows/JOB_tests.yml

  documentation:
    name: Documentation
    uses: ./.github/workflows/JOB_generate_documentation.yml
    secrets: inherit

  success:
    needs: [run_tests, documentation]
    if : ${{ success() }}
    name: Success
    runs-on: ubuntu-latest
    steps:
      - name: Set branch status to success
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { context } = require('@actions/github');
            const { owner, repo } = context.repo;
            const sha = context.sha;
            await github.rest.repos.createCommitStatus({
              owner: owner,
              repo: repo,
              sha: sha,
              state: 'success',
              context: 'continuous-integration/github-action',
              description: 'The build succeeded!'
            });
